### ISSUE TITLE
Needs to run in a writeable directory

### ISSUE THREAD

**Issue by max-allan-surevine** [bitnami/bitnami-docker-cosign#1]
**Description**

When using  `COSIGN_EXPERIMENTAL=1 cosign verify ...` it tries to create a ~/.sigstore directory and can't with this container because the whole container is all owned by root with no permissions. And the default user has no defined home directory.

**Steps to reproduce the issue:**

```
docker run  --rm -e  COSIGN_EXPERIMENTAL=1 bitnami/cosign verify quay.io/openshift-release-dev/ocp-release    
panic: initializing tuf: updating local metadata and targets: creating targets dir: mkdir /.sigstore: permission denied

goroutine 1 [running]:
github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioroots.Get.func1()
	github.com/sigstore/cosign/cmd/cosign/cli/fulcio/fulcioroots/fulcioroots.go:68 +0x74
sync.(*Once).doSlow(0xc000181d00, 0x1c)
	sync/once.go:68 +0xd2
sync.(*Once).Do(...)
........etc......
```

**Describe the results you received:**

See above error.

**Describe the results you expected:**
If I exec into the same container with UID=0 then do the same command :
```
# COSIGN_EXPERIMENTAL=1 cosign verify quay.io/openshift-release-dev/ocp-release           
Error: entity not found in registry
main.go:52: error during command execution: entity not found in registry
```
OK, it didn't verify a signature, but it tried to verify. Whereas before it fails to run.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

Either set the user's home directory to /tmp or actually create a home

**Comment by dgomezleon** [comment]
Hello @max-allan-surevine ,

Thanks a lot for your feedback. 

The [latest tag](https://github.com/bitnami/bitnami-docker-cosign/releases/tag/1.8.0-debian-10-r32) fixes it ( [change](https://github.com/bitnami/bitnami-docker-cosign/blob/master/1/debian-10/Dockerfile#L20) ).
